variable "aws_region" {}
variable "vpc_cidr" {}
variable "subnet_cidr" {}
variable "key_name" {}
variable "public_key_path" {}
variable "instance_type" {}
variable "ami" {}
variable "access_key" {}
variable "secret_key" {}
